name: Docker CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker-compose build

      - name: Run Containers
        run: docker-compose up -d

      - name: Run Tests
        run: |
          echo "Run your test commands here"
